import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultProfile,publicSession,type Session,type Extraction,type Feedback} from '../lib/pipeline/schema.ts';
import {sourceRecallPlan} from '../lib/pipeline/source-recall.ts';
import {feedbackFor,feedbackHeading,resolveReview,reviewResolved,teachingFor} from '../lib/pipeline/feedback.ts';
import {gradeObjective,scheduleEvidence} from '../lib/pipeline/scheduling.ts';
import {varyApplications} from '../lib/pipeline/variation.ts';
const extraction:Extraction={width:600,height:300,method:'ocr',issues:[],regions:[{id:'r1',rawText:'We look forward to seeing you.',correction:null,bbox:{x:0,y:0,width:1,height:1},confidence:98,language:'en',kind:'sentence',selected:true,highlighted:false,confirmed:true,issues:[]}]};
function fixture():Session{const p=sourceRecallPlan(extraction,defaultProfile,'capture',['look forward to']);return {id:'s',captureId:'capture',profile:defaultProfile,items:p.items,queue:p.exercises,index:0,feedback:{},answers:{},assisted:{},retried:[]};}
const unsure:Feedback={outcome:'uncertain',expected:'Example',explanation:'Meaning check unavailable.',method:'unavailable'};
for(const decision of ['confident','practise','unsure'] as const){
 test(`${decision} self-review remains unverified and cannot change recall timing`,()=>{
  const s=fixture(),f=resolveReview(unsure,decision);assert.equal(f.outcome,'uncertain');assert.equal(f.method,'learner');assert.equal(reviewResolved(f),true);assert.doesNotMatch(feedbackHeading(f),/correct/i);assert.equal(scheduleEvidence(s.queue[1],f,3),null);
 });
}
test('an unanswered uncertainty requires a reflection before continuing',()=>{assert.equal(reviewResolved(unsure),false);});
test('old self-reviewed correct answers are never shown as verified',()=>{const s=fixture();const f=feedbackFor(s.queue[1],{outcome:'correct',expected:'x',explanation:'Reviewed by you. Compare your answer.',assisted:true});assert.equal(f.outcome,'uncertain');assert.equal(f.reviewDecision,'confident');assert.match(feedbackHeading(f),/Self-reviewed/);assert.equal(scheduleEvidence(s.queue[1],f,4),null);});
test('independent recall progresses across sessions regardless of self-review',()=>{const s=fixture(),now=new Date('2026-10-05T00:00:00Z');let streak=0;for(let n=0;n<3;n++){const t=scheduleEvidence(s.queue[0],gradeObjective(s.queue[0],'look forward to'),streak,now)!;streak=t.streak;assert.equal(scheduleEvidence(s.queue[1],resolveReview(unsure,'practise'),streak,now),null);}assert.equal(streak,3);assert.equal(scheduleEvidence(s.queue[0],gradeObjective(s.queue[0],'look forward to'),1,now)?.dueAt,'2026-10-08T00:00:00.000Z');});
test('source assistance and AI sentence grading do not overwrite recall evidence',()=>{const s=fixture();assert.equal(scheduleEvidence(s.queue[0],{...gradeObjective(s.queue[0],'look forward to'),assisted:true},4),null);assert.equal(scheduleEvidence(s.queue[1],{outcome:'incorrect',expected:'example',explanation:'Use -ing.',method:'model'},4),null);});
test('a genuinely missed independent recall still schedules another review',()=>{const s=fixture(),t=scheduleEvidence(s.queue[0],gradeObjective(s.queue[0],'wrong'),4,new Date('2026-10-05T00:00:00Z'));assert.deepEqual(t,{streak:0,dueAt:'2026-10-06T00:00:00.000Z'});});
test('recap distinguishes independent recall, errors and uncertain usage, not mastery',()=>{const s=fixture(),[recall,open]=s.queue;s.feedback[recall.id]=gradeObjective(recall,'look forward to');s.feedback[open.id]=resolveReview(unsure,'confident');s.answers[open.id]='I look forward to meet you yesterday.';s.index=2;const recap=publicSession(s).summary!;assert.equal(recap.independentRecall,1);assert.equal(recap.unverified,1);assert.equal(recap.needsPractice,0);assert.equal(recap.items[0].unverified[0].answer,s.answers[open.id]);assert.equal(recap.items[0].checkedApplication,false);s.feedback[recall.id]=gradeObjective(recall,'look up');s.answers[recall.id]='look up';assert.equal(publicSession(s).summary!.needsPractice,1);assert.equal(publicSession(s).summary!.items[0].mistakes[0].expected,'look forward to');});
test('recap and teaching notes never reveal future answers before checking',()=>{const s=fixture(),p=publicSession(s);assert.equal(p.summary,null);assert.equal(p.teaching,null);assert.equal('answer' in p.exercise!,false);s.feedback[s.queue[0].id]=gradeObjective(s.queue[0],'wrong');assert.ok(publicSession(s).teaching);assert.equal(publicSession(s).summary,null);});
test('meaning feedback uses lesson explanations and names unknown meanings honestly',()=>{const i=fixture().items[0];assert.match(teachingFor(i).usage,/-ing/);assert.equal(teachingFor(i).basis,'reference');const unknown=teachingFor({...i,form:'in'});assert.equal(unknown.meaning,null);assert.equal(unknown.quote,i.source.quote);const known=teachingFor({...i,sense:'anticipation',explanation:'Used for a future event.'});assert.equal(known.meaning,'anticipation');assert.equal(known.usage,'Used for a future event.');});
test('application rotates meaningful tasks while recall and source remain intact',()=>{const s=fixture(),prompts=new Set<string>();for(let n=0;n<3;n++){const q=varyApplications(s.queue,s.items,s.profile,n);prompts.add(q[1].prompt);assert.deepEqual(q[0],s.queue[0]);assert.deepEqual(q[1].source,s.queue[1].source);assert.equal(q[1].type,'open');}assert.equal(prompts.size,3);assert.equal(s.queue[1].prompt,'Write your own sentence using “look forward to”.');});
test('variation does not replace model-checked tasks',()=>{const s=fixture();s.items[0].sense='anticipate with pleasure';assert.deepEqual(varyApplications(s.queue,s.items,s.profile,2),s.queue);});

test('explicit source definitions are reused verbatim without guessing other meanings',()=>{const i=fixture().items[0];const tip=teachingFor({...i,form:'reliable',source:{...i.source,quote:'reliable — someone you can trust'}});assert.equal(tip.basis,'source-note');assert.equal(tip.meaning,'someone you can trust');assert.equal(teachingFor({...i,form:'reliable',source:{...i.source,quote:'A reliable friend is here.'}}).meaning,null);});
