import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultProfile,publicSession,type Session,type Exercise} from '../lib/pipeline/schema.ts';
import {prepareQuestion,recordTutorAttempt,markHelp,revealTeaching,hintFor,isAssisted,recentExposure} from '../lib/pipeline/tutoring.ts';
import {gradeObjective,scheduleEvidence} from '../lib/pipeline/scheduling.ts';
import {tutoringQueue} from '../lib/pipeline/variation.ts';
const item={id:'i',language:'en',form:'resilient',kind:'vocabulary' as const,sense:'able to recover after difficulty',explanation:'An adjective describing a person or thing that recovers.',example:'She stayed resilient.',topic:'Study',source:{captureId:'c',regionId:'r',quote:'A consistent routine helps you become more resilient.'},matchItemId:null,selectionReason:'Useful'};
const recall:Exercise={id:'r',itemId:'i',phase:'recall',type:'cloze',prompt:'Complete the captured sentence.',context:'A consistent routine helps you become more ____.',contextKind:'captured',choices:[],answer:'resilient',alternatives:[],explanation:item.explanation,source:item.source};
const meaning:Exercise={...recall,id:'m',phase:'recognition',type:'meaning',prompt:'What does resilient mean here?',context:item.source.quote,choices:['able to recover','sleepy','late'],answer:'able to recover'};
function fixture():Session{return {id:'s',captureId:'c',profile:defaultProfile,items:[item],queue:[recall,meaning],index:0,feedback:{},answers:{},assisted:{},retried:[],tutor:{version:1,steps:{},exposedIds:[],dueIds:['i'],newIds:[],memory:{i:{difficulties:['grammar'],helpedAttempts:1,reflection:'I used resilient as a verb.'}},reflection:''}};}
test('due reviews attempt recall before recognition across all items',()=>{const second={...recall,id:'r2',itemId:'j'};assert.deepEqual(tutoringQueue([meaning,recall,{...meaning,id:'m2',itemId:'j'},second],new Set(['i','j'])).map(e=>e.id),['r','r2','m','m2']);});
test('cold recall hides prior notes, full source, answer and explanation',()=>{const s=fixture();prepareQuestion(s);const p=publicSession(s);assert.equal(p.exercise!.source.quote,'');assert.equal(p.coaching!.memory,null);assert.equal(p.feedback,null);assert.equal(p.teaching,null);assert.equal(p.assisted,false);assert.equal('answer' in p.exercise!,false);});
test('first incorrect attempt receives a hint with no answer or teaching notes',()=>{const s=fixture();prepareQuestion(s);recordTutorAttempt(s,recall,'sleepy',{...gradeObjective(recall,'sleepy'),assisted:false,diagnosis:'retrieval'});const p=publicSession(s);assert.equal(p.coaching!.stage,'revise');assert.equal(p.feedback,null);assert.equal(p.teaching,null);assert.equal(p.coaching!.attemptCount,1);assert.doesNotMatch(p.coaching!.hints.join(' '),/resilient/);assert.equal(p.assisted,true);});
test('revision preserves the original error and separates assisted success in recap',()=>{const s=fixture();prepareQuestion(s);recordTutorAttempt(s,recall,'sleepy',{...gradeObjective(recall,'sleepy'),assisted:false});recordTutorAttempt(s,recall,'resilient',{...gradeObjective(recall,'resilient'),assisted:isAssisted(s,recall)});s.index=2;const recap=publicSession(s).summary!;assert.equal(recap.independentRecall,0);assert.equal(recap.items[0].assistedRecall,true);assert.equal(recap.items[0].revised,true);assert.equal(recap.items[0].mistakes[0].answer,'sleepy');});
test('the original independent failure schedules review, a corrected revision cannot advance it',()=>{const s=fixture(),now=new Date('2026-10-07');const f={...gradeObjective(recall,'wrong'),assisted:false};recordTutorAttempt(s,recall,'wrong',f);assert.equal(scheduleEvidence(recall,f,4,now)?.streak,0);const revised={...gradeObjective(recall,'resilient'),assisted:isAssisted(s,recall)};assert.equal(scheduleEvidence(recall,revised,4,now),null);});
test('a source or hint before answering cannot earn independent recall',()=>{const s=fixture();prepareQuestion(s);markHelp(s,recall);const f={...gradeObjective(recall,'resilient'),assisted:isAssisted(s,recall)};assert.equal(scheduleEvidence(recall,f,2),null);});
test('earlier teaching makes later recall practice with help',()=>{const s=fixture();s.queue=[meaning,recall];prepareQuestion(s);recordTutorAttempt(s,meaning,meaning.answer,gradeObjective(meaning,meaning.answer));s.index=1;prepareQuestion(s);assert.equal(isAssisted(s,recall),true);});
test('overlapping quotes are counted as exposure for other targets',()=>{const s=fixture();s.items.push({...item,id:'j',form:'routine'});s.queue.push({...recall,id:'j-r',itemId:'j',answer:'routine',context:'A consistent ____ helps you become more resilient.'});prepareQuestion(s);assert.ok(s.tutor!.exposedIds.includes('j'));assert.equal(isAssisted(s,recall),false);});
test('revealed explanations mark future recall assisted',()=>{const s=fixture();revealTeaching(s,meaning);assert.equal(isAssisted(s,recall),true);});
test('objective hints cannot contain the saved answer',()=>{const f={...gradeObjective(recall,'wrong'),hint:'The answer is resilient.',nextHint:'Try resilient.'};assert.doesNotMatch(hintFor(recall,item,f,1),/resilient/);assert.doesNotMatch(hintFor(recall,item,f,2),/resilient/);});
test('five unsuccessful attempts provide a bounded path to teaching',()=>{const s=fixture();for(let n=0;n<5;n++)recordTutorAttempt(s,recall,`wrong${n}`,gradeObjective(recall,'wrong'));assert.equal(publicSession(s).coaching!.stage,'feedback');assert.equal(publicSession(s).feedback!.expected,'resilient');assert.ok(publicSession(s).teaching);});
test('resume preserves coaching stage, original responses, hints and reflection',()=>{const s=fixture();recordTutorAttempt(s,recall,'wrong',gradeObjective(recall,'wrong'));s.tutor!.reflection='Check adjective patterns.';const restored=publicSession(JSON.parse(JSON.stringify(s)));assert.equal(restored.coaching!.stage,'revise');assert.equal(restored.coaching!.attemptCount,1);assert.equal(restored.answer,'wrong');assert.equal(restored.reflection,'Check adjective patterns.');});

test('help seen in an earlier session remains visible to the next day’s assessment policy',()=>{const s=fixture();markHelp(s,recall);assert.ok(recentExposure([s],new Date(Date.now()-86400000).toISOString()).has('i'));s.tutor!.exposedAt!['i']='2020-01-01T00:00:00.000Z';assert.equal(recentExposure([s],new Date(Date.now()-86400000).toISOString()).size,0);});
test('old recaps do not offer an unsupported reflection editor',()=>{const s=fixture();delete s.tutor;s.index=2;assert.equal(publicSession(s).reflection,undefined);});

test('short targets are not exposed by unrelated substrings or generic recall instructions',()=>{const s=fixture();s.items[0]={...item,form:'in'};s.queue[0]={...recall,prompt:'Complete the captured text with its original word or phrase.',context:'I live ____ Seoul.',answer:'in'};prepareQuestion(s);assert.equal(isAssisted(s,s.queue[0]),false);});
