'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Bookmark,Plus,Settings2,ImagePlus,BookOpen,X,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Profile,type Extraction,type Region,type SavedCapture,type PublicSession,type Plan,defaultProfile,languages,textOf,sourceRecallNotice} from '@/lib/pipeline/schema';
import {filterCaptures} from '@/lib/pipeline/library';
import {difficultyLabels} from '@/lib/pipeline/tutoring';
import {applicationStyles,applicationLabels} from '@/lib/pipeline/variation';
import {needsReview,textWarnings} from '@/lib/pipeline/extraction';
import {selectedForms as parseForms} from '@/lib/pipeline/text-matching';
import {readScreenshot} from '@/lib/read-screenshot';
import {feedbackHeading,reviewResolved} from '@/lib/pipeline/feedback';
import {TeachingPanel,SessionRecap} from './practice-feedback';

type Library={lastSession:PublicSession|null;captures:SavedCapture[];profile:Profile|null;modelAvailable:boolean;schedule:Array<{item_id:string;due_at:string}>;sources:Array<{item_id:string;capture_id:string;region_id:string;quote:string}>};
const empty:Library={lastSession:null,captures:[],profile:null,modelAvailable:false,schedule:[],sources:[]};
type Replies={library:Library;profile:{profile:Profile};extract:{capture:SavedCapture};captures:{capture:SavedCapture};generate:{plan:Plan;notice:string|null};session:{session:PublicSession};answer:{session:PublicSession}};
async function api<K extends keyof Replies>(path:K,body?:unknown):Promise<Replies[K]>{const res=await fetch(`/api/v2/${path}`,body instanceof FormData?{method:'POST',body}:body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const result=await res.json() as Replies[K]&{error?:string};if(!res.ok)throw new Error(result.error||'Please try again.');return result;}
function localExtraction(c:SavedCapture,p:Profile):Extraction{return c.extraction??{width:1,height:1,method:'legacy',issues:['This older capture has no saved text positions.'],regions:[{id:'legacy',rawText:c.text,correction:null,bbox:{x:0,y:0,width:1,height:1},confidence:0,language:p.targetLanguage,kind:'unknown',selected:true,highlighted:false,confirmed:false,issues:['Check the original text before practising.']}]};}

export default function Studio(){
 const [library,setLibrary]=useState<Library>(empty),[loaded,setLoaded]=useState(false),[view,setView]=useState<'library'|'practice'>('library');
 const [error,setError]=useState(''),[busy,setBusy]=useState(''),[settings,setSettings]=useState(false),[profile,setProfile]=useState<Profile>(defaultProfile);
 const [review,setReview]=useState<SavedCapture|null>(null),[draft,setDraft]=useState<Extraction|null>(null),[forms,setForms]=useState(''),[captureTitle,setCaptureTitle]=useState(''),[draftStatus,setDraftStatus]=useState('');
 const [source,setSource]=useState<{capture:SavedCapture;regionId?:string;questionQuote?:string}|null>(null),[session,setSessionState]=useState<PublicSession|null>(null),[answer,setAnswer]=useState(''),[tokens,setTokens]=useState<number[]>([]),[resumeId,setResumeId]=useState<string|null>(null);
 const [query,setQuery]=useState(''),[filterLanguage,setFilterLanguage]=useState(''),[topic,setTopic]=useState(''),[dueOnly,setDueOnly]=useState(false);
 const dialogOpeners=useRef<Partial<Record<'settings'|'review'|'source',HTMLElement>>>({});
 const libraryHeading=useRef<HTMLHeadingElement>(null);
 function rememberOpener(kind:'settings'|'review'|'source'){if(document.activeElement instanceof HTMLElement&&!document.activeElement.closest('[role=dialog]'))dialogOpeners.current[kind]=document.activeElement;}
 function restoreOpener(kind:'settings'|'review'|'source',event:Event){event.preventDefault();const target=dialogOpeners.current[kind];if(target?.isConnected&&!target.matches(':disabled'))target.focus();else (practiceHeading.current??libraryHeading.current)?.focus();}
 function openSettings(){rememberOpener('settings');setSettings(true);}
 function openSource(next:NonNullable<typeof source>){if(!source)rememberOpener('source');if(session?.exercise&&!session.done){void run('Opening source…',async()=>{const data=await api('answer',{sessionId:session.id,exerciseId:session.exercise!.id,action:'source'});setSession(data.session);setSource(next);});}else setSource(next);}
 function clearFilters(){setQuery('');setFilterLanguage('');setTopic('');setDueOnly(false);}
 const input=useRef<HTMLInputElement>(null),feedbackRef=useRef<HTMLDivElement>(null),practiceHeading=useRef<HTMLHeadingElement>(null);
 async function refresh(){const data=await api('library');setLibrary(data);if(data.profile)setProfile(data.profile);return data as Library;}
 useEffect(()=>{api('library').then(data=>{setLibrary(data);if(data.profile)setProfile(data.profile);else setSettings(true);try{setResumeId(localStorage.getItem('recollect-session'));}catch{ /* Storage may be unavailable in private browsing. */ }}).catch(e=>setError(e.message)).finally(()=>setLoaded(true));},[]);
 function setSession(next:PublicSession|null){
  if(next?.id!==session?.id||next?.index!==session?.index||next?.done!==session?.done){
   let value=next?.answer||'',order:number[]=[];setDraftStatus('');
   try{if(next?.exercise&&!next.feedback){const saved=JSON.parse(localStorage.getItem(`recollect-draft:${next.id}:${next.exercise.id}`)||'null');if(saved&&typeof saved.answer==='string'&&saved.answer.length<=2000){value=saved.answer;order=Array.isArray(saved.tokens)?saved.tokens.filter((n:unknown)=>Number.isInteger(n)&&Number(n)>=0&&Number(n)<next.exercise!.choices.length):[];setDraftStatus('Draft restored from this browser.');}}}catch{ /* A malformed draft never blocks practice. */ }
   setAnswer(value);setTokens(order);
  }
  if(next?.feedback&&next.exercise){try{localStorage.removeItem(`recollect-draft:${next.id}:${next.exercise.id}`);}catch{}setDraftStatus('');}
  setSessionState(next);
  // A historical recap is independent of the learner's unfinished session.
  if(next&&!next.done){setResumeId(next.id);try{localStorage.setItem('recollect-session',next.id);}catch{}}
  else if(next?.done&&next.id===resumeId){setResumeId(null);try{localStorage.removeItem('recollect-session');}catch{}}

 }
 function saveAnswer(value:string,order:number[]=[]){
  setAnswer(value);setTokens(order);
  if(!session?.exercise||session.feedback)return;
  try{localStorage.setItem(`recollect-draft:${session.id}:${session.exercise.id}`,JSON.stringify({answer:value,tokens:order}));setDraftStatus(value?'Draft saved in this browser.':'');}catch{setDraftStatus('Draft could not be saved in this browser. Check your answer before leaving.');}
 }
 useEffect(()=>{practiceHeading.current?.focus();if(practiceHeading.current)window.scrollTo({top:0,behavior:'auto'});},[session?.id,session?.index,session?.done]);
 useEffect(()=>{if(session?.feedback)feedbackRef.current?.focus();},[session?.feedback]);
 const active=library.profile??profile;
 async function run(label:string,fn:()=>Promise<void>){setBusy(label);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy('');}}
 function openReview(c:SavedCapture,keepForms?:string[]){rememberOpener('review');setError('');setCaptureTitle(c.title);setDraft(structuredClone(localExtraction(c,active)));setForms((keepForms??c.selectedForms??c.plan?.items.map(i=>i.form)??[]).join('\n'));setReview(c);}
 async function saveProfile(){await run('Saving settings…',async()=>{const data=await api('profile',profile);setLibrary(l=>({...l,profile:data.profile}));setSettings(false);});}
 async function importFile(file?:File){if(!file)return;if(!library.profile){openSettings();return;}await run('Reading screenshot…',async()=>{
  if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024)throw new Error('Choose a PNG, JPG, or WebP under 8 MB.');
  const bitmap=await createImageBitmap(file);const {width,height}=bitmap;bitmap.close();if(width>20000||height>20000||width*height>40000000)throw new Error('This image is too large. Crop it to the language content.');
  const extraction=await readScreenshot(file,active,width,height,setBusy);
  setBusy(library.modelAvailable?'Checking the screenshot…':'Saving screenshot…');const form=new FormData();form.set('image',file);form.set('extraction',JSON.stringify(extraction));const result=await api('extract',form);await refresh();
  if((!result.capture.extraction||needsReview(result.capture.extraction,active))||!library.modelAvailable)openReview(result.capture);else await build(result.capture);
 });if(input.current)input.current.value='';}
 async function build(c:SavedCapture,selectedForms?:string[]){setBusy('Preparing and checking practice…');const result=await api('generate',{id:c.id,forms:selectedForms??c.selectedForms??c.plan?.items.map(i=>i.form)??[]});await refresh();if(!result.plan.exercises.length||result.plan.reviewItems.length){openReview({...c,plan:result.plan},selectedForms);throw new Error(result.plan.reviewItems.map(i=>i.reason).join(' ')||'There is not enough certain language content for practice.');}const data=await api('session',{captureId:c.id});setSession(data.session);setReview(null);setView('practice');}
 async function practise(c:SavedCapture){if(!library.profile){openSettings();return;}if(!c.extraction||needsReview(c.extraction,active)||!c.plan?.exercises.length){openReview(c);return;}await run('Opening practice…',async()=>{if(c.notice?.startsWith('Source recall')&&(library.modelAvailable||c.notice!==sourceRecallNotice)){await build(c);return;}try{const data=await api('session',{captureId:c.id});setSession(data.session);setView('practice');}catch(e){if(e instanceof Error&&e.message.includes('settings changed'))await build(c);else throw e;}});}
 async function saveReview(practice:boolean){if(!review||!draft)return;await run('Saving reviewed text…',async()=>{const chosen=parseForms(forms);if(chosen.length>4||chosen.some(s=>s.length>100))throw new Error('Choose up to four words or phrases, one per line, with no more than 100 characters each.');const extraction={...draft,regions:draft.regions.map(r=>({...r,confirmed:r.selected}))};if(!extraction.regions.some(r=>r.selected&&textOf(r).trim()&&r.language===active.targetLanguage))throw new Error('Select readable content in your target language.');const {capture}=await api('captures',{id:review.id,title:captureTitle,selectedForms:chosen,extraction});await refresh();if(practice)await build(capture,chosen);else setReview(null);});}
 function editRegion(id:string,change:Partial<Region>){setDraft(d=>d?{...d,regions:d.regions.map(r=>r.id===id?{...r,...change}:r)}:d);}
 async function sessionAction(action:string,extra:Record<string,unknown>={}){if(!session||(!session.exercise&&action!=='reflect'))return;await run(action==='check'?'Checking answer…':action==='hint'?'Preparing a hint…':'Saving…',async()=>{const data=await api('answer',{sessionId:session.id,exerciseId:session.exercise?.id,attempt:session.coaching?.attemptCount,action,...extra});setSession(data.session);if(data.session.done)await refresh();});}
 async function viewSource(){rememberOpener('source');const e=session?.exercise;if(!e)return;const c=library.captures.find(c=>c.id===e.source.captureId);if(!c)return;await run('Opening source…',async()=>{const data=await api('answer',{sessionId:session!.id,exerciseId:e.id,action:'source'});setSession(data.session);setSource({capture:c,regionId:e.source.regionId,questionQuote:e.source.quote});});}
 const ready=library.captures.filter(c=>c.plan?.exercises.length),due=new Set(library.schedule.filter(s=>s.due_at<=new Date().toISOString()).map(s=>s.item_id));
 const visibleCaptures=filterCaptures(library.captures,{query,language:filterLanguage,topic,dueOnly},due);
 const topics=[...new Set(library.captures.map(c=>c.collection))].sort();
 const filtered=!!(query||filterLanguage||topic||dueOnly);
 const e=session?.exercise;
 const coaching=session?.coaching;
 return <div className="app-shell">
  <header className="topbar"><Link className="brand" href="/" aria-label="Recollect home" onClick={()=>setView('library')}><Bookmark size={22} strokeWidth={2}/><span>Recollect</span></Link><nav aria-label="Main navigation"><button aria-current={view==='library'?'page':undefined} className={view==='library'?'active':''} onClick={()=>setView('library')}>Library</button><button aria-current={view==='practice'?'page':undefined} className={view==='practice'?'active':''} onClick={()=>setView('practice')}>Practice</button></nav><button className="icon-button" aria-label="Learning settings" onClick={openSettings}><Settings2 size={20}/></button></header>
  <main>
   {error&&<div className="error" role="alert"><span>{error}{error.includes('Sign in')&&<> <a href="/signin-with-chatgpt?return_to=/">Sign in</a></>}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={18}/></button></div>}
   {busy&&<div className="working" role="status"><span className="spinner"/>{busy}</div>}
   {!loaded?<p className="empty-copy">Loading your library…</p>:view==='library'?<>
    <div className="view-heading"><h1 ref={libraryHeading} tabIndex={-1}>Library</h1><button className="primary" disabled={!!busy} onClick={()=>library.profile?input.current?.click():openSettings()}><Plus size={18}/>Add screenshot</button></div>
    <input ref={input} type="file" className="sr-only" aria-label="Choose screenshot" accept="image/png,image/jpeg,image/webp" onChange={event=>importFile(event.target.files?.[0])}/>
    {!!library.captures.length&&<section className="library-tools" aria-label="Find screenshots"><label className="library-search">Search screenshots<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search titles, text or phrases"/></label><div className="library-filters"><label>Language<select value={filterLanguage} onChange={event=>setFilterLanguage(event.target.value)}><option value="">All languages</option>{Object.entries(languages).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label>Topic<select value={topic} onChange={event=>setTopic(event.target.value)}><option value="">All topics</option>{topics.map(t=><option key={t} value={t}>{t}</option>)}</select></label><label className="due-filter"><input type="checkbox" checked={dueOnly} onChange={event=>setDueOnly(event.target.checked)}/>Due for review</label></div><div className="filter-summary"><p role="status">{visibleCaptures.length} of {library.captures.length} screenshots</p>{filtered&&<button className="text-button" onClick={clearFilters}>Clear filters</button>}</div></section>}
    {!library.captures.length?<div className="empty-state" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(!busy)importFile(event.dataTransfer.files[0]);}}><ImagePlus size={30}/><h2>Add your first screenshot</h2><p>Import language you want to practise. You can also drop an image here.</p><button disabled={!!busy} onClick={()=>library.profile?input.current?.click():openSettings()}>Add screenshot</button></div>:!visibleCaptures.length?<div className="empty-state"><h2>No matching screenshots</h2><p>Try another phrase or clear your filters.</p><button onClick={clearFilters}>Show all screenshots</button></div>:<div className="capture-list">{visibleCaptures.map(c=><article className="capture-row" key={c.id}>
     <button className="thumbnail" aria-label={`View source: ${c.title}`} onClick={()=>openSource({capture:c})}>{c.imageKey?<img alt="" src={`/api/image/${c.id}`}/>:<BookOpen size={28}/>}</button>
     <div className="capture-body"><div className="metadata">{new Date(c.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}{c.collection!=='Unsorted'&&<span>{c.collection}</span>}</div><h2>{c.title}</h2>
      {c.plan?.items.length?<div className="item-forms">{c.plan.items.map(i=><span key={i.id}>{i.form}{library.sources.filter(s=>s.item_id===i.id).length>1&&<small> · {library.sources.filter(s=>s.item_id===i.id).length} sources</small>}</span>)}</div>:<p className="muted">{c.extraction?'Text ready to review':'Review text to create practice'}</p>}
      <div className="row-actions"><button className="text-button" disabled={!!busy} onClick={()=>openReview(c)}>Review text</button><button className="text-button" onClick={()=>openSource({capture:c})}>View source</button><button disabled={!!busy} onClick={()=>practise(c)}>Practise</button></div>
     </div></article>)}</div>}
   </>:<>
    <div className="view-heading"><h1 ref={practiceHeading} tabIndex={-1}>Practice</h1>{session&&!session.done&&<span className="muted">{session.index+1} of {session.total}</span>}</div>
    {session?.done&&resumeId&&<div className="resume-banner"><p>You have unfinished practice saved.</p><button className="primary" disabled={!!busy} onClick={()=>run('Opening session…',async()=>{const data=await api('session',{resume:resumeId});setSession(data.session);})}>Continue unfinished practice</button></div>}
    {!session?<div className="practice-start">{library.lastSession&&<button disabled={!!busy} onClick={()=>setSession(library.lastSession)}>View last recap</button>}{resumeId&&<button className="primary" disabled={!!busy} onClick={()=>run('Opening session…',async()=>{const data=await api('session',{resume:resumeId});setSession(data.session);})}>Continue practice</button>}{ready.length?<div className="practice-list">{ready.map(c=><button key={c.id} disabled={!!busy} onClick={()=>practise(c)}><span>{c.title}<small>{c.plan?.items.some(i=>due.has(i.id))?'Ready for review':!library.schedule.some(s=>c.plan?.items.some(i=>i.id===s.item_id))?'Not practised yet':`Next review ${new Date(Math.min(...library.schedule.filter(s=>c.plan?.items.some(i=>i.id===s.item_id)).map(s=>new Date(s.due_at).getTime()))).toLocaleDateString()}`}</small></span><span>Practise</span></button>)}</div>:<div className="empty-state"><BookOpen size={30}/><h2>No practice yet</h2><p>Add a screenshot and review its text to begin.</p><button onClick={()=>setView('library')}>Open library</button></div>}</div>:session.done?<SessionRecap key={session.id} session={session} onReflect={note=>sessionAction('reflect',{note})} schedule={library.schedule} busy={!!busy} onLibrary={()=>{setSession(null);setView('library');}} onPractise={ids=>run('Preparing focused practice…',async()=>{const data=await api('session',{captureId:session.captureId,focusItemIds:ids});setSession(data.session);})}/>:e&&<div className="practice-card">
     <div className="question-top"><span>{e.phase==='recognition'?'Meaning in context':e.phase==='recall'?'Recall':'Use it in context'}</span><button className="text-button" disabled={!!busy} onClick={viewSource}>View source</button></div>
     {coaching&&<p className="practice-purpose">{e.phase==='recall'?(coaching.assessment==='due'?'Start with what you remember. Hints and the source are here if you need them.':coaching.assessment==='initial'?'Let’s find a useful starting point. Try what you know, or ask for help.':'A little extra practice. This is separate from your next due review.'):'Try it, use a hint if needed, and revise. You can reveal the explanation at any time.'}</p>}
     {e.context&&<div className="question-context"><span className="eyebrow">{e.contextKind==='new'?'New example':e.contextKind==='corrected'?'Corrected source text':'Captured text'}</span><p lang={active.targetLanguage}>{e.context}</p></div>}
     <h2 className="prompt">{e.prompt}</h2>
     {e.type==='open'&&!library.modelAvailable&&<p className="connection-note">This writing task is self-reviewed. Meaning and grammar will not be checked automatically.</p>}
     {e.type==='open'&&!session.feedback&&(!coaching||coaching.attemptCount===0)&&<label className="task-choice">Choose your writing task<select aria-label="Writing task" value={session.writingStyle??''} disabled={!!busy} onChange={event=>{if(event.target.value)sessionAction('style',{style:event.target.value});}}>{!session.writingStyle&&<option value="">Current task</option>}{applicationStyles.map(style=><option value={style} key={style}>{applicationLabels[style]}</option>)}</select><small>Your draft stays saved when you change the task.</small></label>}
     <form onSubmit={event=>{event.preventDefault();sessionAction('check',{answer});}}>
      {['meaning','collocation'].includes(e.type)?<fieldset className="choices" disabled={!!session.feedback||!!busy}><legend className="sr-only">Choose an answer</legend>{e.choices.map((choice,n)=><label key={n} className={answer===choice?'chosen':''}><input type="radio" name="answer" value={choice} checked={answer===choice} onChange={()=>saveAnswer(choice)}/><span>{choice}</span></label>)}</fieldset>:e.type==='reorder'?<div className="reorder"><div className="assembled" aria-live="polite">{answer||'Choose the words in order.'}</div><div className="tokens">{e.choices.map((word,n)=><button type="button" key={n} disabled={tokens.includes(n)||!!session.feedback||!!busy} onClick={()=>{const next=[...tokens,n];saveAnswer(next.map(i=>e.choices[i]).join(' '),next);}}>{word}</button>)}<button type="button" className="icon-button" aria-label="Reset word order" disabled={!!session.feedback||!!busy} onClick={()=>{saveAnswer('');}}><RotateCcw size={18}/></button></div></div>:<label className="answer-field">Your answer{e.type==='open'?<textarea value={answer} maxLength={2000} disabled={!!session.feedback||!!busy} onChange={event=>saveAnswer(event.target.value)} rows={3} placeholder="Write a short response"/>:<input autoComplete="off" value={answer} maxLength={2000} disabled={!!session.feedback||!!busy} onChange={event=>saveAnswer(event.target.value)} placeholder="Word or phrase"/>}</label>}
      {!session.feedback&&draftStatus&&<p className="draft-status muted" role="status">{draftStatus}</p>}
      {!session.feedback&&<div className="question-actions"><button className="primary" disabled={!answer.trim()||!!busy}>{e.type==='open'&&!library.modelAvailable?'Save for review':coaching?.stage==='revise'?'Check revision':'Check'}</button>{session.assisted&&<small>Practice with help · saved separately from independent recall</small>}</div>}
     </form>
     {coaching&&!session.feedback&&<section className="coaching-panel" aria-label="Hints and revision" aria-live="polite">
      {coaching.stage==='revise'&&<><h3>Try a revision</h3><p>Your answer needs another look. Your first attempt is saved; use the hint and edit your answer above.</p></>}
      {coaching.hints.map((hint,n)=><p key={n}><strong>Hint {n+1}: </strong>{hint}</p>)}
      <div className="row-actions">{coaching.canHint&&<button disabled={!!busy} onClick={()=>sessionAction('hint')}>{coaching.hints.length?'Give me another hint':'Give me a hint'}</button>}<button className="text-button" disabled={!!busy} onClick={()=>sessionAction('reveal')}>Show explanation</button></div>
     </section>}
     {coaching?.memory&&(coaching.memory.difficulties.length>0||coaching.memory.reflection)&&<details className="learning-memory"><summary>Your earlier practice notes</summary>{coaching.memory.difficulties.length>0&&<p>Recent difficulties: {[...new Set(coaching.memory.difficulties)].map(d=>difficultyLabels[d]).join(', ')}. Use this as a focus, not a score.</p>}{coaching.memory.reflection&&<p><span className="eyebrow">Your reflection</span>{coaching.memory.reflection}</p>}</details>}
     {session.feedback&&<div ref={feedbackRef} tabIndex={-1} className={`feedback ${session.feedback.outcome}`} aria-live="polite"><strong>{coaching?.revealed&&!coaching.attemptCount?'Studied with help':feedbackHeading(session.feedback)}</strong>
      <p className="feedback-basis">{session.feedback.method==='objective'?'Checked against the saved answer. This does not verify your own sentence use.':session.feedback.method==='model'?'AI feedback can make mistakes. Check uncertain usage with your source or a teacher.':'Your confidence is a reflection, not a correctness score.'}</p>
      <p><span className="muted">{e.type==='open'?(session.feedback.referenceOnly||library.captures.find(c=>c.id===session.captureId)?.notice?.startsWith('Source recall')?'Source wording for comparison: ':'Possible answer: '):'Expected answer: '}</span>{session.feedback.expected}</p><p>{session.feedback.explanation}</p>
      {session.feedback.scheduleNote&&<p className="schedule-note">{session.feedback.scheduleNote}</p>}
      {session.teaching&&<details className="learning-memory" open={coaching?.revealed&&session.feedback.outcome==='incorrect'}><summary>Explore meaning, use & source</summary><TeachingPanel teaching={session.teaching}/></details>}
      {!reviewResolved(session.feedback)?<div className="self-review"><p>How do you feel about your response?</p><div className="row-actions"><button disabled={!!busy} onClick={()=>sessionAction('resolve',{decision:'practise'})}>I need more practice</button><button disabled={!!busy} onClick={()=>sessionAction('resolve',{decision:'confident'})}>I feel confident</button><button disabled={!!busy} onClick={()=>sessionAction('resolve',{decision:'unsure'})}>I’m still unsure</button></div></div>:<button className="primary" disabled={!!busy} onClick={()=>sessionAction('continue')}>Continue</button>}</div>}
    </div>}
   </>}
  </main>
  <Dialog open={settings} onOpenChange={open=>{if(!busy)setSettings(open);}}><DialogContent className="settings-panel" onCloseAutoFocus={event=>restoreOpener('settings',event)}><DialogTitle>Learning settings</DialogTitle><DialogDescription>Used to choose language and practice that fits you.</DialogDescription>{error&&<p className="error" role="alert">{error}</p>}<form onSubmit={event=>{event.preventDefault();saveProfile();}} className="settings-form"><label>Target language<select value={profile.targetLanguage} onChange={event=>setProfile(p=>({...p,targetLanguage:event.target.value as Profile['targetLanguage']}))}>{Object.entries(languages).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label>Approximate level<select value={profile.level} onChange={event=>setProfile(p=>({...p,level:event.target.value as Profile['level']}))}>{['A1 · Beginner','A2 · Elementary','B1 · Intermediate','B2 · Upper intermediate','C1 · Advanced','C2 · Proficient'].map(label=><option key={label} value={label.slice(0,2)}>{label}</option>)}</select></label><label>Learning goal<textarea rows={2} maxLength={240} minLength={3} required value={profile.goal} onChange={event=>setProfile(p=>({...p,goal:event.target.value}))}/></label>{!library.modelAvailable&&<p className="connection-note">Contextual lessons need a model connection. For now, choose phrases yourself and practise source recall.</p>}<button className="primary" disabled={!!busy}>Save settings</button></form></DialogContent></Dialog>
  <Dialog open={!!review} onOpenChange={open=>{if(!open&&!busy)setReview(null);}}><DialogContent className="review-panel" onCloseAutoFocus={event=>restoreOpener('review',event)}><DialogTitle>Review text</DialogTitle><DialogDescription>Select the language content you want to practise. Check it against the screenshot.</DialogDescription>{error&&<p className="error" role="alert">{error}</p>}{busy&&<p className="working" role="status">{busy}</p>}{review&&draft&&<><label className="capture-title-field">Screenshot title<input value={captureTitle} maxLength={120} onChange={event=>setCaptureTitle(event.target.value)}/></label>
   <div className="review-grid"><div className="source-image">{review.imageKey?<div className="image-regions"><img src={`/api/image/${review.id}`} alt="Original screenshot"/>{draft.method!=='legacy'&&draft.regions.map((r,n)=><button key={r.id} className={`region-box ${r.selected?'selected':''}`} style={{left:`${r.bbox.x*100}%`,top:`${r.bbox.y*100}%`,width:`${r.bbox.width*100}%`,height:`${r.bbox.height*100}%`}} aria-label={`Select region ${n+1}`} onClick={()=>editRegion(r.id,{selected:!r.selected})}><span>{n+1}</span></button>)}</div>:<p className="muted">The original image was not saved for this capture.</p>}</div><div className="region-list">{draft.regions.map((r,n)=><section key={r.id} className={`region-editor ${r.selected?'':'excluded'}`}><label className="region-select"><input type="checkbox" checked={r.selected} onChange={event=>editRegion(r.id,{selected:event.target.checked})}/><strong>Region {n+1}</strong><span>{r.kind==='interface'?'Interface text':r.kind==='unknown'?'Check content':r.kind}</span></label><p className="raw-text" lang={r.language}>{r.rawText||'No readable text found.'}</p>{r.selected&&<><div className="region-options"><label>Language<select value={r.language} onChange={event=>editRegion(r.id,{language:event.target.value})}><option value="und">Choose language</option>{Object.entries(languages).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label className="interest"><input type="checkbox" checked={r.highlighted} onChange={event=>editRegion(r.id,{highlighted:event.target.checked})}/>Focus on this</label></div>{r.issues.length>0&&!r.confirmed&&<p className="review-issue">{r.issues.filter(issue=>!issue.startsWith('Check “|”')).join(' ')}</p>}{textWarnings(textOf(r)).map(warning=><p key={warning} className="review-issue">{warning}</p>)}<details open={r.correction!==null||!r.rawText}><summary>Correct text</summary><label className="correction-label">Correction (original stays saved)<textarea value={r.correction??r.rawText} onChange={event=>editRegion(r.id,{correction:event.target.value===r.rawText?null:event.target.value})} rows={2}/></label></details></>}</section>)}</div></div>
   {<label className="forms-field">Words or phrases to practise <span className="muted">(up to 4, one per line)</span><textarea rows={3} maxLength={800} value={forms} onChange={event=>setForms(event.target.value)} placeholder={"would like\nWell, actually"}/><small>Keep commas inside a phrase. Capital letters, apostrophe styles and Japanese OCR spaces can differ from the source.</small><small>{library.modelAvailable?'Optional: leave empty to let the assistant suggest targets.':'Source recall only. Meanings and open responses require your review.'}</small></label>}
   <div className="dialog-actions"><button disabled={!!busy} onClick={()=>saveReview(false)}>Save text</button><button className="primary" disabled={!!busy||(!library.modelAvailable&&!forms.trim())} onClick={()=>saveReview(true)}>Practise</button></div>
  </>}</DialogContent></Dialog>
  <Dialog open={!!source} onOpenChange={open=>{if(!open)setSource(null);}}><DialogContent className="source-panel" onCloseAutoFocus={event=>restoreOpener('source',event)}><DialogTitle>Source</DialogTitle><DialogDescription>{source?.capture.title}</DialogDescription>{source&&<>{source.questionQuote&&<div className="source-text"><span className="eyebrow">Text used for this question</span><p>{source.questionQuote}</p></div>}<div className="source-image">{source.capture.imageKey&&<div className="image-regions"><img src={`/api/image/${source.capture.id}`} alt="Original screenshot"/>{source.regionId&&source.capture.extraction?.method!=='legacy'&&source.capture.extraction?.regions.filter(r=>r.id===source.regionId).map(r=><span key={r.id} className="source-highlight" style={{left:`${r.bbox.x*100}%`,top:`${r.bbox.y*100}%`,width:`${r.bbox.width*100}%`,height:`${r.bbox.height*100}%`}}/>)}</div>}</div>{(source.capture.extraction?.regions??[]).filter(r=>!source.regionId||r.id===source.regionId).map(r=><div key={r.id} className="source-text"><span className="eyebrow">Original captured text</span><p>{r.rawText}</p>{r.correction!==null&&<><span className="eyebrow">Learner correction</span><p>{r.correction}</p></>}</div>)}{!source.capture.extraction&&<p>{source.capture.text}</p>}{!source.regionId&&source.capture.plan?.items.map(i=><div className="source-text" key={i.id}><strong>{i.form}</strong><span className="eyebrow">{i.sense.startsWith('Unverified')?'Source recall':'Generated explanation'}</span><p>{i.explanation}</p>{i.example&&<><span className="eyebrow">New example</span><p>{i.example}</p></>}{library.sources.filter(s=>s.item_id===i.id&&s.capture_id!==source.capture.id).map(s=><button className="text-button" key={s.capture_id+s.region_id} onClick={()=>{const c=library.captures.find(c=>c.id===s.capture_id);if(c)setSource({capture:c,regionId:s.region_id});}}>View another source</button>)}</div>)}</>}</DialogContent></Dialog>
 </div>;
}
