'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Bookmark,Plus,Layers,BookOpen,Target,ImagePlus,Sparkles,Check,CheckCircle2,ChevronLeft,ChevronRight,X,Upload,RotateCcw,ExternalLink,ScanText,FolderOpen,Image as ImageIcon,LoaderCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Sidebar,SidebarProvider} from '@/components/ui/sidebar';
import {type Capture,type Card,type Library,DEFAULT_GOAL,DEMO_CAPTURES,makeCards,suggestTerms,suggestCollection,checkAnswer} from '@/lib/learning';
type Session={cards:Card[];index:number;mode:'flashcards'|'quiz';revealed:boolean;answer:string;checked:boolean;correct:boolean;score:number;done:boolean};
async function api<T = Record<string,unknown>>(path:string,body?:unknown){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});let d:Record<string,unknown>;try{d=await r.json() as Record<string,unknown>}catch{throw new Error('Your library is temporarily unavailable. Please try again.')}if(!r.ok)throw new Error(String(d.error||'Could not save your changes. Please try again.'));return d as T;}
export default function Studio(){
 const [library,setLibrary]=useState<Library>({captures:[],reviews:[],goal:DEFAULT_GOAL});
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [login,setLogin]=useState(false);
 const [view,setView]=useState('library');const [filter,setFilter]=useState('All collections');const [demo,setDemo]=useState(false);
 const [upload,setUpload]=useState(false);const [goalOpen,setGoalOpen]=useState(false);const [goalDraft,setGoalDraft]=useState(DEFAULT_GOAL);
 const [detail,setDetail]=useState<Capture|null>(null);const [session,setSession]=useState<Session|null>(null);const [busy,setBusy]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null);
 async function load(){setLoading(true);try{const d=await api<Library>('/api/library');setLibrary(d);setGoalDraft(d.goal);if(d.captures.length===0)setDemo(true);setLogin(false);setError('');}catch(e){const msg=(e as Error).message;setLogin(msg.includes('Sign in'));setError(msg);}finally{setLoading(false);}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id)},[notice]);
 const captures=demo?DEMO_CAPTURES:library.captures;
 const cards=useMemo(()=>captures.flatMap(makeCards),[captures]);
 const collections=[...new Set(captures.map(c=>c.collection))];
 const shown=filter==='All collections'?captures:captures.filter(c=>c.collection===filter);
 const practiceCards=cards.filter(c=>filter==='All collections'||c.collection===filter);
 const practiced=library.reviews.filter(r=>r.attempts>0).length;
 function start(mode:'flashcards'|'quiz',deck=practiceCards){if(!deck.length)return;setSession({cards:deck,index:0,mode,revealed:false,answer:'',checked:false,correct:false,score:0,done:false});setView('practice');}
 async function record(correct:boolean){if(!session||busy)return;setBusy(true);try{if(!demo){const card=session.cards[session.index];await api('/api/review',{id:crypto.randomUUID(),cardId:card.id,correct});}setSession({...session,checked:true,revealed:true,correct,score:session.score+(correct?1:0)});}catch(e){setError((e as Error).message);}finally{setBusy(false)}}
 function next(){if(!session)return;if(session.index+1>=session.cards.length){setSession({...session,done:true});if(!demo)void load();}else setSession({...session,index:session.index+1,answer:'',revealed:false,checked:false,correct:false});}
 async function saveGoal(){if(!goalDraft.trim())return;setBusy(true);try{await api('/api/goal',{goal:goalDraft});setLibrary({...library,goal:goalDraft.trim()});setGoalOpen(false);setNotice('Learning goal updated');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function leaveDemo(){setDemo(false);setFilter('All collections');setSession(null);setView('library')}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const ac=new AbortController();try{Promise.resolve(context.registerTool({name:'open_screenshot_import',title:'Open screenshot import',description:'Open the screenshot import form. Does not upload or save a screenshot.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');setUpload(true);return {opened:true}}},{signal:ac.signal})).catch(()=>{});}catch{}return()=>ac.abort()},[]);
 const current=session?.cards[session.index];
 return <div className="studio-shell">
  <header className="topbar"><a href="/" className="brand" aria-label="Recollect home"><span className="brand-mark"><Bookmark size={23}/></span>recollect<span className="brand-dot">.</span></a><span className="top-caption">YOUR SCREENSHOT LEARNING STUDIO</span><button className="avatar" onClick={()=>setGoalOpen(true)} aria-label="Edit your learning goal"><Target size={20}/></button></header>
  <SidebarProvider className="workspace"><Sidebar collapsible="none" className="sidebar"><div><p className="eyebrow">WORKSPACE</p><button className={'nav-button '+(view==='library'?'selected':'')} onClick={()=>{setView('library');setSession(null)}}><Layers size={19}/>My library<span>{captures.length}</span></button><button className={'nav-button '+(view==='practice'?'selected':'')} onClick={()=>setView('practice')}><BookOpen size={19}/>Practice<span>{cards.length}</span></button></div><div className="sidebar-bottom"><div className="goal-card"><Target size={21}/><p className="eyebrow">MY LEARNING GOAL</p><p>{library.goal}</p><button onClick={()=>setGoalOpen(true)} className="text-button">Edit goal</button></div><div className="prototype-note"><span className="mini-label">WORKING PROTOTYPE</span><p>English text recognition.<br/>Practice from your own words.</p></div></div></Sidebar>
  <main className="main"><Tabs className="mobile-nav" value={view} onValueChange={setView}><TabsList><TabsTrigger value="library">My library</TabsTrigger><TabsTrigger value="practice">Practice</TabsTrigger></TabsList></Tabs><div className="breadcrumb">My workspace <span>/</span> {view==='library'?'Library':'Practice'}</div>
  {error&&<div className="alert" role="alert"><span>{error}</span>{login?<a href="/signin-with-chatgpt?return_to=/" target="_top" className="text-button">Sign in</a>:<button className="text-button" onClick={()=>void load()}>Retry connection</button>}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
  {demo&&<div className="demo-banner"><span><Sparkles size={16}/>Example collection · Your activity here is not saved</span><button onClick={leaveDemo}>Back to my library</button></div>}
  <div className="page-heading"><div><p className="eyebrow blue">CAPTURE. CONNECT. PRACTISE.</p><h1 ref={heading}>{view==='library'?'A second life for your screenshots.':'Make it stick.'}</h1><p className="subtitle">{view==='library'?'Turn the language you notice into the language you know.':'A little practice, connected to where you found it.'}</p></div><button className="button primary" onClick={()=>setUpload(true)}><Plus size={19}/>Add screenshot</button></div>
  {view==='library'?<>
   <div className="overview"><div><span className="stat-number">{captures.length.toString().padStart(2,'0')}</span><span>screenshots collected</span></div><div><span className="stat-number">{cards.length.toString().padStart(2,'0')}</span><span>practice cards ready</span></div><div><span className="stat-number">{collections.length.toString().padStart(2,'0')}</span><span>connected collections</span></div><div className="overview-note"><span className="tiny-star">✦</span><p>A screenshot is just<br/>the beginning.</p></div></div>
   <div className="section-top"><h2>Your collections <span>{collections.length}</span></h2><div className="section-actions">{!demo&&<button className="text-button" onClick={()=>{setDemo(true);setFilter('All collections')}}>Explore an example</button>}<button className="button small" disabled={!cards.length} onClick={()=>start('flashcards')}><BookOpen size={16}/>Practise all</button></div></div>
   {loading&&!demo?<div className="empty-state"><LoaderCircle className="spin"/><h3>Opening your library…</h3></div>:captures.length===0?<div className="empty-state"><div className="empty-icon"><ImagePlus size={34}/></div><h3>Save something worth remembering.</h3><p>Add a screenshot from an article, a video, or your notes.<br/>We’ll turn its words into a small practice set.</p><button className="button primary" onClick={()=>setUpload(true)}><Plus size={17}/>Add your first screenshot</button><button className="text-button" onClick={()=>setDemo(true)}>Try an example first</button></div>:<><div className="collection-grid">{collections.map((name,i)=>{const items=captures.filter(c=>c.collection===name),deck=cards.filter(c=>c.collection===name);return <article className={'collection-card tone-'+(i%3)} key={name}><div className="collection-art"><span className="collection-number">0{i+1}</span><div className="paper-stack"><div className="paper-back"/><div className="paper-front"><span className="paper-label">{items[0].source||'YOUR CAPTURE'}</span><p>{items[0].text.slice(0,145)}</p><span className="paper-highlight">{items[0].terms[0]||'Something to remember'}</span></div></div><span className="art-icon"><FolderOpen size={22}/></span></div><div className="collection-body"><div className="collection-title"><h3>{name}</h3><span className="count-pill">{deck.length} cards</span></div><p>{items.length} screenshot{items.length!==1?'s':''} · {items.slice(0,2).flatMap(c=>c.terms.slice(0,2)).join(', ')}</p><div className="collection-footer"><button className="text-button" onClick={()=>setFilter(filter===name?'All collections':name)}>View screenshots</button><button className="round-button" aria-label={`Practise ${name}`} disabled={!deck.length} onClick={()=>start('flashcards',deck)}><BookOpen size={18}/></button></div></div></article>})}</div>
   <div className="section-top captures-heading"><h2>{filter==='All collections'?'Recent captures':filter}</h2>{filter!=='All collections'&&<button className="text-button" onClick={()=>setFilter('All collections')}>Show all</button>}</div><div className="capture-list">{shown.map(c=><button className="capture-row" key={c.id} onClick={()=>setDetail(c)}><span className="capture-thumb">{c.imageKey?<img src={`/api/image/${c.id}`} alt=""/>:<ScanText size={25}/>}</span><span className="capture-main"><strong>{c.title}</strong><span>{c.source||'Screenshot'}{c.demo?' · Example content':''}</span></span><span className="capture-collection">{c.collection}</span><span className="capture-card-count">{makeCards(c).length} cards</span><ChevronRight size={17}/></button>)}</div></>}
  </>:session&&current?<div className="practice-stage">{session.done?<div className="session-end"><span className="completion-icon"><CheckCircle2 size={42}/></span><p className="eyebrow">SESSION COMPLETE</p><h2>A little more familiar.</h2><p>You practised {session.cards.length} words and recalled {session.score} of them.</p>{demo&&<p className="muted">This was an example session. Add a screenshot to start your own.</p>}<div className="button-row"><button className="button primary" onClick={()=>start(session.mode,session.cards)}>Practise again</button><button className="button" onClick={()=>{setSession(null);setView('library')}}>Back to library</button></div></div>:<><div className="practice-top"><button className="text-button" onClick={()=>setSession(null)}><ChevronLeft size={16}/>Exit practice</button><span>{session.mode==='quiz'?'Context quiz':'Flashcards'} · {session.index+1} of {session.cards.length}</span></div><Progress value={(session.index/session.cards.length)*100} aria-label="Session progress"/><div className="flashcard"><span className="tag">{current.collection}</span><p className="eyebrow">{session.mode==='quiz'?'COMPLETE THE ORIGINAL SENTENCE':'RECALL THE MISSING WORD'}</p><h2>{current.prompt}</h2>{session.mode==='quiz'&&!session.checked?<form onSubmit={e=>{e.preventDefault();void record(checkAnswer(session.answer,current.term))}}><label className="sr-only" htmlFor="answer">Missing word</label><input id="answer" value={session.answer} onChange={e=>setSession({...session,answer:e.target.value})} placeholder="Type the missing word…" autoComplete="off" autoFocus/><button className="button primary" disabled={!session.answer.trim()||busy}>Check answer</button></form>:!session.revealed?<button className="button primary" onClick={()=>setSession({...session,revealed:true})}>Reveal word</button>:<div className="answer-reveal" aria-live="polite"><strong>{current.term}</strong>{session.checked&&<p>{session.correct?'You remembered it.':'One to practise again.'}</p>}</div>}
   {session.revealed&&!session.checked&&<div className="button-row"><button className="button" disabled={busy} onClick={()=>void record(false)}><RotateCcw size={16}/>Still learning</button><button className="button primary" disabled={busy} onClick={()=>void record(true)}><Check size={16}/>Remembered</button></div>}{session.checked&&<button className="button primary" onClick={next}>{session.index+1===session.cards.length?'Finish session':'Next word'}</button>}
   <button className="source-link" onClick={()=>setDetail(captures.find(c=>c.id===current.captureId)||null)}><ImageIcon size={15}/>View original context</button></div></>}</div>:<div className="practice-chooser"><div className="section-top"><h2>Your next small step</h2><span className="muted">{demo?0:practiced} cards practised</span></div><div className="practice-options"><button className="practice-option" disabled={!cards.length} onClick={()=>start('flashcards',cards)}><span className="option-icon"><Layers size={28}/></span><h3>Flip & remember</h3><p>Recall a word from its original sentence. Reveal it when you’re ready.</p><span className="text-button">Start flashcards · {cards.length} cards</span></button><button className="practice-option" disabled={!cards.length} onClick={()=>start('quiz',cards)}><span className="option-icon coral"><BookOpen size={28}/></span><h3>Put it to the test</h3><p>Fill in the missing words from the moments you captured.</p><span className="text-button">Start a quiz · {cards.length} questions</span></button></div>{!cards.length&&<p className="muted">Add a screenshot with vocabulary, or <button className="text-button" onClick={()=>setDemo(true)}>try an example collection</button>.</p>}</div>}
  <footer className="workspace-footer"><span><Bookmark size={14}/>Collected by you. Connected for practice.</span><span>English · Context-based practice</span></footer>
  </main></SidebarProvider>
  <Dialog open={upload} onOpenChange={setUpload}><DialogContent className="import-dialog"><ImportForm captures={library.captures} goal={library.goal} onSaved={async(name,count)=>{setUpload(false);leaveDemo();await load();setNotice(`${count} practice cards added to ${name}`)}}/></DialogContent></Dialog>
  <Dialog open={goalOpen} onOpenChange={setGoalOpen}><DialogContent><DialogTitle>What are you learning for?</DialogTitle><DialogDescription>Your goal stays with your library as you collect new language.</DialogDescription><label className="field-label" htmlFor="goal">Learning goal</label><textarea id="goal" maxLength={240} value={goalDraft} onChange={e=>setGoalDraft(e.target.value)} rows={3}/><p className="help">Shared words connect related screenshots. Topic cues and your goal help suggest a collection; you can change it before saving.</p><p className="help" role="alert">{error}</p><button className="button primary" disabled={busy||!goalDraft.trim()} onClick={()=>void saveGoal()}>Save goal</button></DialogContent></Dialog>
  <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="source-dialog"><DialogTitle>{detail?.title}</DialogTitle><DialogDescription>{detail?.source||'Original screenshot'} · {detail?.collection}</DialogDescription>{detail?.imageKey?<img className="original-image" src={`/api/image/${detail.id}`} alt={`Original screenshot: ${detail.title}`}/>:<div className="original-text"><span className="mini-label">{detail?.demo?'AUTHORED EXAMPLE':'CAPTURED TEXT'}</span><p>{detail?.text}</p></div>}<div className="terms">{detail?.terms.map(t=><span className="term" key={t}>{t}</span>)}</div><button className="button primary" onClick={()=>{if(detail){start('flashcards',makeCards(detail));setDetail(null)}}}>Practise these words</button></DialogContent></Dialog>
  {notice&&<div className="toast" role="status"><CheckCircle2 size={19}/>{notice}</div>}
 </div>
}
function ImportForm({captures,goal,onSaved}:{captures:Capture[];goal:string;onSaved:(name:string,count:number)=>void}){
 const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState('');const [text,setText]=useState('');const [title,setTitle]=useState('');const [source,setSource]=useState('');const [terms,setTerms]=useState('');const [collection,setCollection]=useState('');const [busy,setBusy]=useState(false);const [reading,setReading]=useState(false);const [progress,setProgress]=useState(0);const [error,setError]=useState('');const [mode,setMode]=useState('image');
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 async function choose(f?:File){if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>8*1024*1024){setError('Choose a PNG, JPG, or WebP image under 8 MB.');return;}setFile(f);setText('');setTerms('');setCollection('');setPreview(URL.createObjectURL(f));setTitle(f.name.replace(/\.[^.]+$/,''));setError('');setReading(true);setProgress(0);let worker;try{const {createWorker}=await import('tesseract.js');worker=await createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')setProgress(Math.round(m.progress*100))}});const {data}=await worker.recognize(f);setText(data.text.trim());setTerms(suggestTerms(data.text).join(', '));setCollection(suggestCollection(data.text,captures,goal).name);if(!data.text.trim())setError('No text was found. Try a clearer image or enter the text below.');}catch{setError('Text recognition could not finish. You can still enter the screenshot text below.');}finally{await worker?.terminate();setReading(false)}}
 const chosenTerms=terms.split(',').map(t=>t.trim()).filter(Boolean);const count=makeCards({id:'preview',title,text,terms:chosenTerms,collection,source,createdAt:''}).length;
 async function save(){setBusy(true);setError('');try{const form=new FormData();if(mode==='image'&&file)form.set('image',file);form.set('metadata',JSON.stringify({id:crypto.randomUUID(),title:title.trim(),text:text.trim(),terms:chosenTerms,collection:collection.trim(),source:source.trim()}));const r=await fetch('/api/captures',{method:'POST',body:form});const data=await r.json() as {error?:string;capture:Capture;cardCount:number};if(!r.ok)throw new Error(data.error||'Unable to save. Your text is still here; try again.');onSaved(data.capture.collection,data.cardCount);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><DialogTitle>Add something worth remembering</DialogTitle><DialogDescription>Capture the context. Leave with a little practice.</DialogDescription><Tabs value={mode} onValueChange={setMode}><TabsList><TabsTrigger value="image">Screenshot</TabsTrigger><TabsTrigger value="text">Paste text</TabsTrigger></TabsList></Tabs>
 {mode==='image'&&<label className={'upload-zone '+(preview?'has-preview':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!reading)void choose(e.dataTransfer.files[0])}}>{preview?<img src={preview} alt="Screenshot to import"/>:<><Upload size={26}/><strong>Drop a screenshot here</strong><span>or choose a file · PNG, JPG, WebP · up to 8 MB</span></>}<input type="file" aria-label="Choose screenshot" accept="image/png,image/jpeg,image/webp" disabled={reading||busy} onChange={e=>void choose(e.target.files?.[0])}/>{preview&&<span className="replace-image">Choose another screenshot</span>}</label>}
 {reading&&<div className="ocr-progress" role="status"><span><LoaderCircle size={16} className="spin"/>Reading your screenshot… {progress}%</span><Progress value={progress}/></div>}
 {error&&<div className="alert" role="alert">{error}</div>}
 <div className="form-grid"><label>Title<input value={title} maxLength={120} onChange={e=>setTitle(e.target.value)} placeholder="A phrase I want to remember"/></label><label>Source <span className="optional">optional</span><input value={source} maxLength={160} onChange={e=>setSource(e.target.value)} placeholder="Article, video, lecture…"/></label></div>
 <label className="field-label">{mode==='image'?'Review the extracted text':'Text to practise'}<textarea value={text} maxLength={15000} onChange={e=>setText(e.target.value)} rows={4} placeholder="Paste or correct the original sentences here…"/></label>
 <div className="suggestion-row"><p className="help">Keep full sentences so each word has context.</p><button className="text-button" disabled={!text.trim()||reading} onClick={()=>{setTerms(suggestTerms(text).join(', '));setCollection(suggestCollection(text,captures,goal).name)}}><Sparkles size={14}/>Suggest words & collection</button></div>
 <label className="field-label">Words to practise<input value={terms} maxLength={600} onChange={e=>setTerms(e.target.value)} placeholder="curiosity, resilient, a little room"/></label><p className="help">Separate words or phrases with commas. Each must appear in a full sentence above.</p>
 <label className="field-label">Collection<input value={collection} maxLength={80} onChange={e=>setCollection(e.target.value)} placeholder="Everyday expressions" list="collections"/></label><datalist id="collections">{[...new Set(captures.map(c=>c.collection))].map(c=><option key={c} value={c}/>)}</datalist>
 <div className="import-footer"><span>{count} practice card{count!==1?'s':''} ready</span><button className="button primary" disabled={busy||reading||!title.trim()||!collection.trim()||!text.trim()||count===0||(mode==='image'&&!file)} onClick={()=>void save()}>{busy?<LoaderCircle className="spin" size={17}/>:<Plus size={17}/>}Create practice materials</button></div><p className="help privacy-note">Text recognition runs in your browser. Saving stores the screenshot and practice text in your private library. English only in this prototype.</p></>
}
